apiVersion: gauravkr19.dev/v1alpha1
kind: MyResource
metadata:
  labels:
    app.kubernetes.io/name: myresource
    app.kubernetes.io/instance: myresource-sample
    app.kubernetes.io/part-of: myresource
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: myresource
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  # image of crud app
  image: {{ .Values.myResource.image }}
  imageDB: {{ .Values.myResource.imageDB }}
  deploymentReplicas: 1
  statefulSetReplicas: 1

  # Original size of PVC
  pvcSize: {{ .Values.myResource.pvcSize }}

  # Is PVC extension needed?
  pvcExtensionNeeded: {{ .Values.myResource.pvcExtensionNeeded }}
  
  # New size of PVC  
  newPVCSize: {{ .Values.myResource.newPVCSize }}

  # Secret value for database and application. has database credentials
  secretData:
    required: true
    dbUser: {{ .Values.myResource.secretData.dbUser }}
    dbPassword: {{ .Values.myResource.secretData.dbPassword }}
